### PR TITLE
fix Incorrect DiffInMonths calculation #59 

### PR DESCRIPTION
**Pull request by rendyreivaldy25**
added condition check if diffInMonths > 0, so diffInMonths can work properly.
[issue #59 ](https://github.com/uniplaces/carbon/issues/59#issue-776436857)

### CODE REVIEW

**Comment by Santos-Luis** [comment]
@tlfbrito @gracoes

**Comment by tlfbrito** [comment]
@rendyreivaldy25 I know it's not your fault, but before merging this we need to fix the CI/CD (current Travis) first.
We want to migrate this to Github Actions.

**Comment by rendyreivaldy25** [comment]
> @rendyreivaldy25
> Thanks for your contribution.
> 
> I know it's not your fault, but before merging this we need to fix the CI/CD (current Travis) first.
> We want to migrate this to Github Actions.

glad to help. please contact me if my code has a problem.

**Comment by tlfbrito** [comment]
@rendyreivaldy25 can you rebase with master?
We migrated the CI to Github Actions and we should now be able to execute the tests again.

**Comment by rendyreivaldy25** [comment]
@tlfbrito I am so sorry. I was so busy until I forgot to check this issue. I made some changes again because in my last works,  different bugs appeared. Right now it should be running okay. Please kindly check if there are other bugs. Thanks

**Comment by rendyreivaldy25** [comment]
> hi @rendyreivaldy25, just left you a suggestion! Let me know what you think :)

Sorry for slow response, of course, I will fox that later. I will update to you soon

**Comment by rntdrts** [comment]
Due to lack of activity - Fixing this on https://github.com/uniplaces/carbon/pull/74

**Pull request closed without merging**
